### ISSUE TITLE
Remove dependency on EAVP

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/january#169]
There are a few classes still depending on EAVP in the forms branch.

1)GeometryComponent- EAVP classes are present but no longer used and can be removed.

2)ResourceHandler- Iterates over all found IVizServices from the IVizServiceFactory to decide whether a file should be used in an ICEResource or a VizResource. VizResource extends ICEResource, and I don't see anything that would break form having ResourceHandler always return a VizResource and ignoring the extra data members provided by the subclass.

3)MeshComponent- This is the biggest one. For compressed XML persistence, it uses several old data structures (the BasicController MVC classes that used to represent data objects) from EAVP that are slated for deletion and replacement with new January classes similar to how the EAVP Geometry classes depend on the January Geometry classes, though this is a large undertaking and improvements to the Mesh Editor like that aren't a current priority. We may just need to move o.e.eavp.modeling into January from now until the time it's removed entirely.

**Comment by jayjaybillings** [comment]
@SmithRWORNL Here are some thoughts.

1) +1.
2) I don't see why this class should be in January or EAVP. This is for some high-level functions in ICE and isn't used anywhere else, (I think), so we should probably move it to org.eclipse.ice.item. However, before we do that we need to figure out if anything else here uses it.
3) Well poop. I'm not sure how we keep making mistakes like this, but we really need to start catching this stuff. This code is so badly written and tangled that we can't use January until we rewrite it. Moving o.e..e.v.modeling doesn't fix it from what I can tell because of dependencies of that package on things are aren't in January, but probably should be. I'll think about it for a bit, but let's fixing this a priority for after your talk on the 8th.
4) Note that VizServiceFactoryHolder also depends on EAVP. So, it needs to go away too. If we can fix 2, then I think we can just delete this class.

**Comment by jayjaybillings** [comment]
Okay. I fixed this. 

1) Removed all references to EAVP from the target, GeometryComponent, Manifests and other classes.
2) Deleted the ResourceHandler.
3) I implemented an entirely new, generic visitation scheme for classes that are not part of the IComponentVisitor interface. I'll write up the details in separate post, but this means that it is safe to delete the old MeshComponent (which I did) from January until we create a new one and visitation will still be possible for client code.
4) Deleted the VizServiceFactoryHolder.

@SmithRWORNL Please add two tickets to @eclipse/eclipse-ice to move the ResourceHandler into o.e.i.item and leave the MeshComponent class o.e.i.datastructures until we create a new one.

**Comment by jonahkichwacoders** [comment]
@jayjaybillings the updated target platform looks great now. Well done on solving the circular dependency (at the target platform level)

**Comment by jayjaybillings** [comment]
Thanks @jonahkichwacoders! I think it is a nice solution that will even let us do some neat things once we have all of this working.
