### ISSUE TITLE
There should be a feature for just using IDataset

### ISSUE THREAD

**Issue by gerring** [eclipse/january#4]
IDataset has few dependencies and should have its own feature to make it easier to import to targets. Should I create this or will you?

**Comment by jonahkichwacoders** [comment]
I'm working on this now and figuring out how to make datasets independent. I have a local build branch which I'll push when I return from holiday next week. I also have a HIPP commissioned to run our builds on now. 

I would like to be able to push January datasets out to new the maven repos too,that is still under investigation.

**Comment by jonahkichwacoders** [comment]
PS. Do you need an actual Eclipse feature? Because of the maintenance overhead of features and their tendency to be incomplete I have been shying away from them for individual bundles.

**Comment by jayjaybillings** [comment]
I guess I'm with both of you on this. Distinct elements should have their own features, even though in this case it seems weird because IDataSet and Forms are individual bundles.

I think it makes a little more sense if you consider that their features also need to include their dependencies. For example, the Forms feature will need to have Glazed Lists in it. (I'm happy to assemble that one btw.)

**Comment by gerring** [comment]
That stuff already pulls in dependencies which I don't require in scanning
(although good that part of January) therefore a feature I could depend on
would help at some point. For now, I have created my own so no massive
hurry.

M

**Comment by jonahkichwacoders** [comment]
My arguments below are about reducing unmaintained code in the future. I don't object to adding features if they are maintained (and actually used!)

> I think it makes a little more sense if you consider that their features also need to include their dependencies. For example, the Forms feature will need to have Glazed Lists in it. 

The problem with the above is that the feature duplicates information, the plug-in manifest already specifies this and the P2 meta data has it too. i.e. consider that the individual orbit bundles have no such dependencies. 

The use of feature.xml makes using import-package at the bundle level rather irrelevant. The reason is that if you tell people to use Features to collect what they need, then you are telling them they have to use specific bundles. Features make sense for a collection of bundles that provide a "feature", especially one that is user visible.

> (I'm happy to assemble that one btw.)
There is already one for form, but at the moment it is not up to date.

> That stuff already pulls in dependencies which
What does "that stuff" refer to here?

**Comment by jonahkichwacoders** [comment]
The release for January allows just the dataset plug-in to be included in a target platform. For an example see  [JanuaryExamples.tpd](https://github.com/eclipse/january/blob/JANUARY_1_0_0/org.eclipse.january.examples/JanuaryExamples.tpd) (or alternatively the generated  [JanuaryExamples.target](https://github.com/eclipse/january/blob/JANUARY_1_0_0/org.eclipse.january.examples/JanuaryExamples.target))

Fixed in d5bbb63dc22bb6c31d7f1bfd38931f92aa94ad03
