### ISSUE TITLE
Dependencies in org.eclipse.january.form?

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/january#58]
The form bundle needs its dependencies cleaned up. 
1. It should not have any dependencies on EAVP, so I'm not sure how anyone has been able to get it to resolve or build...
2. It defines an impossible JPA persistence unit that refers to ICE...
3. It uses the Eclipse Core Runtime for file handling.
4. It uses EMF for managing EMF data in the forms.
5. It uses GlazedLists to create a generic ListComponent that can be used in the Forms.
6. It uses org.slf4j for logging.

1 & 2 just need to be cleaned up. 

My plan to address 3 & 5, which predate's January in my list of concerns, has been to migrate the entire Form's bundle to use an EMF model. This may eliminate most of 4 as well since EMF code tends to be self-contained, but there are some cases - like the EMFComponent - that does other tricky things with EMF models where EMF components may still be used.

So, here are some questions then: What is the threshold for a dependency in January? Shall it have no dependencies outside of itself or are some allowed? If some are allowed, what are they? (Apache seems to be a go given the core January bundle...)

**Comment by jayjaybillings** [comment]
Note that the Form bundle also needs to have some name and documentation updates, but that may be part of #26.

**Comment by jonahkichwacoders** [comment]
> So, here are some questions then: What is the threshold for a dependency in January? Shall it have no dependencies outside of itself or are some allowed? If some are allowed, what are they? (Apache seems to be a go given the core January bundle...)

IMHO dependencies are certainly allowed, many of them in fact. However UI and unnecessary  dependencies on Eclipse Runtime (no definition given here, sorry, but I could give examples if it helps) are problematic.

Simply as I see it January is data structures and algorithms. I know the history so far, especially the less mature Geometry component has some issues in this regard. I have been neck deep in [Xtext (using it for CDT)](https://kichwacoders.com/2016/11/28/pushing-the-limits-of-xtext-for-cc-linker-scripts/) for the last few months and I can see how easy it is to just get all this magic UI stuff for free.

Right now the problem looks worse than it is because the dependencies, both at runtime and dev time, are much more than most everyone seems to be expecting when checking out the project or consuming the p2 site. 

So far we already have January being used in places like IoT and servers, without UI and without workbenches. I want to ensure that it works in all these other environments too, like without OSGi or anything else that does not add specific value for the project.

I hope my rambling has cleared up a couple of things.

**Comment by PeterC-DLS** [comment]
Closing as january-forms was moved to https://github.com/eclipse/january-forms
